<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>The Next Edge Report</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="css/flat-ui.css" rel="stylesheet">
    
    <!-- Loading Isotope & Other CSS -->
    <link rel="stylesheet" type="text/css" href="/css/style.css">

    <link rel="shortcut icon" href="images/favicon.ico">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->
  </head>
  <body>
    <div id="fb-root"></div>
    
    <div class="container">
      <?php include 'header.php'; ?>
      
      <div class="row">
        <div class="span9 homepageIntro">
          <h3 class="demo-panel-title">Introduction</h3>
          
          <p>Welcome to the Next Edge Report!</p>

<p>This is an experiment and reflection exploring the content generated in the Next Edge Facebook Group. We downloaded the data using Facebook's API and built an alternative interface for exploring the content that has been shared over the last two years of the Facebook group's existence. </p>

<p>Our primary line of inquiry - how can different interfaces to the same data enable us to reflect, explore and discover insights about our own community's activity? There is so much value that has already been generated by our community, yet it remains locked to us, in our ability to dive deep into collective self-reflection on the meaning of all of it. Too often important insights, valuable comments and important threads get lost under the avalanche of new content. Communities face an even greater challenge when they scale to wider and more diverse participation - where intent can soon become cloudy.</p>

<p>What can happen if we can access the deep learning that has been generated by this group? Can we answer questions like, what encourages healthy and lasting information sharing? What disrupts communication and breaks down coordination? What kind of knowledge sharing is most conducive to building coherence, coordinating our activities, and helping to facilitate alignment between intent and action?</p>

<p>This is just an initial exploration into a "community dashboard". We envision a future of flexible tools for community self-reflection. As we continue to build out the functionality of this community report, we hope it can act as a dynamic platform where productive patterns can be identified and strengthened by new metrics, methods for filtering, organizing and sensemaking the content we share, so collectively we can engage more deeply with our community's capacity for self-organization.</p>
          <p>Yours in the evolution,</p>
          <p>The Metamaps Team</p>
        </div>
        <div class="span3 homepageBox facebook">
          <h3 class="demo-panel-title">Login</h3>
          <div class="addSpace"><p>
            If you are part of the Next Edge on facebook, you can login and be able to browse the new posts section, which should give you some better features for viewing new content going into the Next Edge, in terms of filtering for just quality content. 
          </p>
          <fb:login-button show-faces="true" width="140" max-rows="1"></fb:login-button></div>
        </div>
      </div> <!-- /row -->
      
      <div class="row">
        <a class="span12 btn btn-warning download" href="#fakelink" >
          Download Our Data
        </a>
      </div> <!-- /row -->
    </div><!-- /container -->
    
    <?php include 'footer.php'; ?>
  </body>
</html>